# token from https://codecov.io/gh/anders-dc/Icepack/settings
codecov:
  token: 9c1a17ac-ff4e-4add-8b8a-9c0d0acffcfd

# do not comment with code coverage metrics in github pull requests
comment: false
