# Test         Grid    PEs        Sets    BFB-compare
smoke          col     1x1        diag1,run1year
smoke          col     1x1        debug,run1year
smoke          col     1x1        debug,bgcISPOL
smoke          col     1x1        debug,bgcNICE
smoke          col     1x1        debug,bgcsklNICE
smoke          col     1x1        debug,run1year,thermo1
smoke          col     1x1        debug,run1year,swccsm3
smoke          col     1x1        debug,run1year,alt01
smoke          col     1x1        debug,run1year,alt02
smoke          col     1x1        debug,run1year,alt03
smoke          col     1x1        debug,run1year,alt04
smoke          col     1x1        debug,run1year,leap,dt30min
smoke          col     1x1        debug,run1year,dyn
smoke          col     1x1        debug,run1year,fsd12
smoke          col     1x1        debug,run1year,fsd1
restart        col     1x1        debug
restart        col     1x1        diag1
restart        col     1x1        pondcesm
restart        col     1x1        pondlvl
restart        col     1x1        pondtopo
restart        col     1x1        bgcISPOL
restart        col     1x1        thermo1
restart        col     1x1        swccsm3
restart        col     1x1        alt01
restart        col     1x1        alt02
restart        col     1x1        alt03
restart        col     1x1        alt04
restart        col     1x1        dyn
restart        col     1x1        fsd12

