# Test         Grid    PEs        Sets    BFB-compare
smoke          col     1x1        diag1,run1year
smoke          col     1x1        debug,run1year
smoke          col     1x1        debug,bgcispol
smoke          col     1x1        debug,bgcnice
smoke          col     1x1        debug,zaero
#smoke          col     1x1        debug,bgcsklnice
smoke          col     1x1        debug,run1year,thermo1
smoke          col     1x1        debug,run1year,swredist
smoke          col     1x1        debug,run1year,swccsm3
smoke          col     1x1        debug,run1year,alt01
smoke          col     1x1        debug,run1year,alt02
smoke          col     1x1        debug,run1year,alt03
smoke          col     1x1        debug,run1year,alt04
smoke          col     1x1        debug,run1year,leap,dt30min
smoke          col     1x1        debug,run1year,dyn
smoke          col     1x1        debug,run1year,fsd12,short
smoke          col     1x1        debug,run1year,fsd1
smoke          col     1x1        debug,run1year,snw30percent,snwgrain
smoke          col     1x1        debug,run1year,snwitdrdg
smoke          col     1x1        debug,run1year,calcdragio
smoke          col     1x1        debug,run1year,modal
smoke          col     1x1        debug,run1year,fluxopenw
smoke          col     1x1        debug,run1year,dyn,fluxopenw
smoke          col     1x1        debug,run1year,debug,snicartest
smoke          col     1x1        debug,run1year,debug,snicar
smoke          col     1x1        debug,run1year,debug,congel
smoke          col     1x1        debug,ionetcdf,atmmosaic,ocnmosaic
restart        col     1x1        debug
restart        col     1x1        diag1
restart        col     1x1        pondlvl
restart        col     1x1        pondtopo
restart        col     1x1        bgcispol
restart        col     1x1        bgcnice
restart        col     1x1        zaero,snwitdrdg,snwgrain
#restart        col     1x1        bgcsklnice
restart        col     1x1        thermo1
restart        col     1x1        swccsm3
restart        col     1x1        isotope
restart        col     1x1        alt01
restart        col     1x1        alt02
restart        col     1x1        alt03
restart        col     1x1        alt04
restart        col     1x1        saltflux
restart        col     1x1        dyn
restart        col     1x1        fsd12,short
restart        col     1x1        snwitdrdg,snwgrain
restart        col     1x1        modal
restart        col     1x1        fluxopenw
restart        col     1x1        snicartest
restart        col     1x1        snicar
restart        col     1x1        congel

