# Test         Grid    PEs        Sets    BFB-compare
smoke          col     1x1        diag1,run1year
smoke          col     1x1        debug,run1year
smoke          col     1x1        debug,bgcispol
smoke          col     1x1        debug,bgcnice
smoke          col     1x1        debug,bgcsklnice
smoke          col     1x1        debug,run1year,thermo1
smoke          col     1x1        debug,run1year,swccsm3
smoke          col     1x1        debug,run1year,alt01
smoke          col     1x1        debug,run1year,leap,dt30min
smoke          col     1x1        debug,run1year,dyn
restart        col     1x1        debug
restart        col     1x1        diag1
restart        col     1x1        pondlvl
restart        col     1x1        pondtopo
restart        col     1x1        bgcispol
restart        col     1x1        thermo1
restart        col     1x1        swccsm3
restart        col     1x1        isotope
restart        col     1x1        alt01
restart        col     1x1        alt02
restart        col     1x1        alt03
restart        col     1x1        alt04
restart        col     1x1        dyn
restart        col     1x1        fsd12,short
restart        col     1x1        snwitdrdg,snwgrain
restart        col     1x1        modal
