#! /bin/csh -f

### Change these to your own site and user directory! 
### You will need to create a Makefile Macro in bld/ and a run_ice script 
### in input_templates/.
setenv SITE LANL.conejo   # also works for mustang

setenv SYSTEM_USERDIR /net/scratch3/eclare/CICE.v6.0  # conejo

setenv RES col 
setenv NXGLOB 4           # number of grid points

setenv NICELYR    7       # number of vertical layers in the ice
setenv NSNWLYR    1       # number of vertical layers in the snow
setenv NICECAT    5       # number of ice thickness categories

### Tracers               # match ice_in tracer_nml to conserve memory
setenv TRAGE   1          # set to 1 for ice age tracer
setenv TRFY    1          # set to 1 for first-year ice area tracer
setenv TRLVL   1          # set to 1 for level and deformed ice tracers
setenv TRPND   1          # set to 1 for melt pond tracers
setenv NTRAERO 1          # number of aerosol tracers 
                          # (up to max_aero in ice_domain_size.F90) 
                          # CESM uses 3 aerosol tracers
setenv TRBRI   0          # set to 1 for brine height tracer
setenv TRZS    0          # set to 1 for zsalinity tracer
                          # (needs TRBRI = 1)
setenv TRBGCS  0          # set to 1 for skeletal layer tracers  
                          # (needs TRBGCZ = 0) 
setenv TRBGCZ  0          # set to 1 for zbgc tracers
                          # (needs TRBGCS = 0 and TRBRI = 1)         
setenv NBGCLYR 7          # number of zbgc layers
setenv TRZAERO 0          # number of z aerosol tracers 
                          # (up to max_aero = 6)
setenv TRALG   0          # number of algal tracers
                          # (up to max_algae = 3)
setenv TRDOC   0          # number of dissolve organic carbon 
                          # (up to max_doc = 3)
setenv TRDIC   0          # number of dissolve inorganic carbon 
                          # (up to max_dic = 1)
setenv TRDON   0          # number of dissolve organic nitrogen
                          # (up to max_don = 1)
setenv TRFEP   0          # number of particulate iron tracers 
                          # (up to max_fe  = 2) 
setenv TRFED   0          # number of dissolved iron tracers 
                          # (up to max_fe  = 2)

### Specialty code
setenv CAM_ICE  no        # set to yes for CAM runs (single column) 
setenv IO_TYPE  netcdf    # set to none if netcdf library is unavailable
setenv THRD     no        # set to yes for OpenMP threading

if !( $THRD == 'yes') setenv OMP_NUM_THREADS 1
if  ( $THRD == 'yes') setenv OMP_NUM_THREADS 2 # positive integer 

### File unit numbers
setenv NUMIN 11           # minimum file unit number
setenv NUMAX 99           # maximum file unit number

### Set SRCDIR and EXEDIR to your own paths!
#setenv SRCDIR /usr/projects/climate/eclare/CICE.v6.0/svn/Icepack  # conejo
setenv SRCDIR /usr/projects/climate/eclare/CICE.v6.0/github/cice.eclare/icepack  # conejo

setenv EXEDIR $SYSTEM_USERDIR/icepack_driver
                                          if !(-d $EXEDIR) mkdir -p $EXEDIR
setenv CBLD   $SRCDIR/configuration/bld  
setenv OBJDIR $EXEDIR/compile           ; if !(-d $OBJDIR) mkdir -p $OBJDIR
setenv HSTDIR $EXEDIR/history           ; if !(-d $HSTDIR) mkdir -p $HSTDIR

setenv ARCH `uname -s`
if ( $ARCH == 'UNICOS/mp') setenv ARCH UNICOS
if ( $ARCH == 'UNICOS') then
   cp -f $CBLD/Makefile.$ARCH $CBLD/Makefile
else if ( $ARCH == 'Darwin' ) then
   cp -f $CBLD/Makefile.$ARCH $CBLD/Makefile
else
   cp -f $CBLD/Makefile.std $CBLD/Makefile
endif
setenv ARCH $ARCH.$SITE

cd $EXEDIR

if !(-e icepack_in)  cp $SRCDIR/configuration/icepack_in .
#if !(-e run_ice) cp $SRCDIR/configuration/bld/run_ice.$ARCH run_ice

cd $OBJDIR

setenv COMMDIR serial

setenv DRVDIR cice

### List of source code directories (in order of importance).
cat >! Filepath << EOF
$SRCDIR/configuration/driver
$SRCDIR/columnphysics/constants/$DRVDIR
$SRCDIR/columnphysics
EOF
#$SRCDIR/source
#$SRCDIR/$COMMDIR
#$SRCDIR/$IODIR

cc -o makdep $CBLD/makdep.c                         || exit 2

gmake VPFILE=Filepath EXEC=$EXEDIR/icepack \
      -f  $CBLD/Makefile MACFILE=$CBLD/Macros.$ARCH || exit 2

cd ..
pwd
echo $NXGLOB  = NXGLOB,  number of cells
if ( $THRD == 'yes') echo $OMP_NUM_THREADS = OMP_NUM_THREADS
echo $TRAGE   = TRAGE,   iage tracer
echo $TRFY    = TRFY,    first-year ice tracer
echo $TRLVL   = TRLVL,   level-ice tracers
echo $TRPND   = TRPND,   melt pond tracers
echo $NTRAERO = NTRAERO, number of aerosol tracers
echo $TRBRI   = TRBRI,   brine height tracer
echo $NBGCLYR = NBGCLYR, number of bio grid layers
echo $TRZS    = TRZS,    zsalinity tracer
echo $TRBGCS  = TRBGCS,  skl BGC tracers
echo $TRBGCZ  = TRBGCZ,  z BGC tracers
echo $TRALG   = TRALG,   number of autotrophs
echo $TRDOC   = TRDOC,   number of DOC pools
echo $TRDIC   = TRDIC,   number of DIC pools
echo $TRDON   = TRDON,   number of DON pools
echo $TRFED   = TRFED,   number of dFe pools
echo $TRFEP   = TRFEP,   number of pFe pools
echo $TRZAERO = TRZAERO, number of z aerosol tracers