name: icepack
channels:
  - conda-forge
  - nodefaults
dependencies:
# Build dependencies
  - compilers
  - make
# Python dependencies for building the HTML documentation
  - sphinx
  - sphinxcontrib-bibtex
